spring:
  profiles:
    active: test
#  main:
#    banner-mode: off
#  boot:
#    admin:
#      client:
#        url: http://localhost:8088

server:
  port: 8081

scheduled:
  time: 5000
  cron: "*/3 * * * * *"

logging:
  level:
    org:
      springframework:
        web: info
    pl:
      klimas7:
        spring: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

info:
  app:
    name: "Spring Boot Application"
    description: "This is my first spring boot application"
    version: "1.0.0"