spring:
  profiles:
    active: test

server:
  port: 8081

scheduled:
  time: 5000
  cron: "*/3 * * * * *"

logging:
  level:
    org:
      springframework:
        web: debug
    pl:
      klimas7:
        spring: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "Spring Boot Application"
    description: "This is my first spring boot application"
    version: "1.0.0"